=== AdmiJW/FrontEnd/XML Tutorial/TV Schedule/tvschedule.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<!-- TVSCHEDULE, the root element -->
<xs:element name='tvSchedule'>
	<xs:complexType>
		<xs:sequence>
			<xs:element name='channel' type='channel' minOccurs='1' maxOccurs='unbounded'/>
		</xs:sequence>
		<xs:attribute name='name' type='xs:string' use='required'/>
	</xs:complexType>
</xs:element>



<xs:complexType name='channel'>
	<xs:sequence>
		<xs:element name='banner' type='xs:string'/>
		<xs:element name='day' type='day' minOccurs='1' maxOccurs='unbounded'/>
	</xs:sequence>
	<xs:attribute name='chan' type='xs:string' use='required'/>
</xs:complexType>



<xs:complexType name='day'>
	<xs:sequence>
		<xs:element name='date' type='xs:date'/>
		<xs:choice>
			<xs:element name='programsLot' type='programsLot' minOccurs='1' maxOccurs='unbounded'/>
			<xs:element name='holiday' type='xs:string'/>
		</xs:choice>
	</xs:sequence>
</xs:complexType>



<xs:complexType name='programsLot'>
	<xs:sequence>
		<xs:element name='time' type='time'/>
		<xs:element name='title' type='title'/>
		<xs:element name='description' type='xs:string'/> 
	</xs:sequence>
	<xs:attribute name='vtr' type='xs:boolean'/>
</xs:complexType>

<xs:simpleType name='time'>
	<xs:restriction base='xs:string'>
		<xs:pattern value='[0-2][0-9]:[0-9][0-9]'/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name='title'>
	<xs:simpleContent>
		<xs:extension base='xs:string'>
			<xs:attributeGroup ref="titleAtt"></xs:attributeGroup>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>


<xs:attributeGroup name="titleAtt">
	<xs:attribute name='rating' type='rating' />
	<xs:attribute name='language' type='language' />
</xs:attributeGroup>

<xs:simpleType name="rating">
	<xs:restriction base='xs:string'>
		<xs:enumeration value="G"/>
		<xs:enumeration value="PG"/>
		<xs:enumeration value='PG13'/>
		<xs:enumeration value='PG18'/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name='language'>
	<xs:restriction base='xs:string'>
		<xs:enumeration value='chinese'/>
		<xs:enumeration value='english'/>
		<xs:enumeration value='malay'/>
		<xs:enumeration value='korean'/>
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== AdmiJW/FrontEnd/XML Tutorial/XML XSD (Schema)/tvschedule.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<tvSchedule name='Singapore'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="tvschedule.xsd"
>
	<channel chan='Channel8'>
		<banner>Channel 8</banner>
		<day>
			<date>2020-08-02</date>
			<programsLot vtr='false'>
				<time>12:00</time>
				<title rating='PG13' language='chinese'>Saturday Cinema: The Vanished Murderer</title>
				<description>Prisoner Fu Yuan digs a tunner in her prison cell and escapes.</description>
			</programsLot>
			<programsLot vtr='true'>
				<time>12:55</time>
				<title rating='PG' language='chinese'>Code of Honour - EP 15</title>
				<description>Tian He puts pressure on Jian Feng to get Ah Zai involved in their illicit dealings.</description>
			</programsLot>
			<programsLot vtr='true'>
				<time>14:50</time>
				<title>It's A Small World Sr 4 - EP 6</title>
				<description>Join Mark Lee and his foreign students as they discuss about undesirable habits when travelling overseas.</description>
			</programsLot>
		</day>
		<day>
			<date>2020-08-30</date>
			<programsLot>
				<time>12:00</time>
				<title rating='PG' language='chinese'>The First Half of My Life - EP 19</title>
				<description>Laojin, the warehouse manager, persues Zijun by taking her to work.</description>
			</programsLot>
			<programsLot vtr='true'>
				<time>14:00</time>
				<title rating='G' language='chinese'>Young Justice Bao - EP 3</title>
				<description>Young Justice Bao, a 1993 series produced by Mediacorp and starring Chew Chor Meng as young Bao Zheng.</description>
			</programsLot>
		</day>
		<day>
			<date>2020-08-09</date>
			<holiday>Singapore National Day</holiday>
		</day>
	</channel>
	
	<channel chan='Channel 5'>
		<banner>Channel 5</banner>
		<day>
			<date>2020-08-02</date>
			<programsLot vtr='false'>
				<time>12:00</time>
				<title rating='PG13' language='korean'>Train To Busan</title>
				<description>Sok-woo, a father with not much time for his daughter, Soo-ahn, are boarding the KTX</description>
			</programsLot>
			<programsLot vtr='true'>
				<time>12:50</time>
				<title rating='PG13' language='english'>Jamestown S2 - EP 1</title>
				<description>A terrible crime throws suspicion on the whole colony</description>
			</programsLot>
			<programsLot vtr='true'>
				<time>15:20</time>
				<title rating="PG">Savage Kingdom - EP 5</title>
				<description>Sekekama, the undisputed King of the Marse Pride lions</description>
			</programsLot>
		</day>
	</channel>
	
</tvSchedule>
